SELECT * FROM crm_project.lead;
RENAME TABLE CRM_PROJECT.LEAD TO CRM_PROJECT.LEADS;
SELECT * FROM LEADS;
ALTER TABLE LEADS CHANGE `#_CONVERTED_ACCOUNTS` `CONVERTED_ACCOUNTS` INT;
ALTER TABLE LEADS CHANGE `#_CONVERTED_OPPORTUNITIES` `CONVERTED_OPPORTUNITIES` INT;

# 1. TOTAL LEADS
SELECT COUNT(*) AS TOTAL_LEADS FROM LEADS;

# 2. EXPECTED AMOUNT FROM CONVERTED LEADS
SELECT CONVERTED, SUM(EXPECTED_AMOUNT) AS EXPECTED_AMOUNT FROM OPPORTUNITY 
INNER JOIN LEADS ON OPPORTUNITY.OPPORTUNITY_ID=LEADS.CONVERTED_OPPORTUNITY_ID
GROUP BY CONVERTED;

# 3. CONVERSION RATE
SELECT CONCAT(ROUND((SUM(CONVERSION_RATE)/COUNT(*)),2),"%") AS CONVERSION_RATE FROM LEADS;

# 4. CONVERTED ACCOUNTS
SELECT SUM(CONVERTED_ACCOUNTS) AS CONVERTED_ACCOUNTS FROM LEADS;

# 5. CONVERTED OPPORTUNITIES
SELECT SUM(CONVERTED_OPPORTUNITIES) AS CONVERTED_OPPORTUNITIES FROM LEADS;

# 6. LEAD BY SOURCE
SELECT LEAD_SOURCE, COUNT(LEAD_ID) AS LEADS FROM LEADS GROUP BY LEAD_SOURCE;

# 7. LEAD BY INDUSTRY
SELECT INDUSTRY, COUNT(LEAD_ID) AS LEADS FROM LEADS GROUP BY INDUSTRY;